FROM node:24-trixie-slim as build
WORKDIR /src
RUN npm install -g @angular/cli@20
COPY . .
RUN npm ci
RUN ng build

FROM nginx:latest as final
COPY --from=build src/dist/dockerangu/browser /usr/share/nginx/html
EXPOSE 80